/*
 * #%L
 * DEWE API
 * %%
 * Copyright (C) 2016 - 2019 Hugo López-Fernández, Aitor Blanco-García, Florentino Fdez-Riverola,
 * 			Borja Sánchez, and Anália Lourenço
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */
package org.sing_group.rnaseq.api.controller;

import java.util.List;
import java.util.Optional;

import org.sing_group.rnaseq.api.entities.ballgownedgeroverlaps.BallgownEdgeROverlaps;
import org.sing_group.rnaseq.api.environment.execution.ExecutionException;
import org.sing_group.rnaseq.api.environment.execution.parameters.VennDiagramConfigurationParameter;

/**
 * The interface for controlling the Ballgown and edgeR DE overlap script
 * working directory where results generated by {@link BallgownEdgeROverlaps} 
 * are stored.
 *
 * @author Hugo López-Fernández
 * @author Aitor Blanco-Míguez
 *
 */
public interface BallgownEdgeROverlapsWorkingDirectoryController {

	/**
	 * If the genes table is present, then it returns the {@code BallgownEdgeROverlaps}
	 * list. Otherwise it returns an empty {@code Optional}.
	 *
	 * @return the {@code BallgownEdgeROverlaps} list wrapped in an {@code Optional}
	 */
	public abstract Optional<BallgownEdgeROverlaps> getOverlaps();

	/**
	 * Returns a list containing the names of the working directory files that
	 * have a view associated to them.
	 *
	 * @return a list containing the names of the working directory files that
	 *         have a view associated to them
	 */
	public abstract List<String> getMissingWorkingDirectoryFiles();


	/**
	 * Creates the figure DE analyses overlap.
	 *
	 * @param imageConfiguration the {@code VennDiagramConfigurationParameter}
	 * @throws ExecutionException if an error occurs during the execution
	 * @throws InterruptedException if an error occurs executing the system
	 *         binary
	 */
	public abstract void createVennDiagram(
			VennDiagramConfigurationParameter imageConfiguration)
		throws ExecutionException, InterruptedException;
}
